apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::666531394927:role/voting-app-node-group-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-05-10T17:25:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "704"
  uid: 3aa340df-9439-44ab-a20a-6c4394de3f1b
