apiVersion: v1
kind: Service
metadata:
   labels:
    app: vote
   name: vote

spec: 
   type: LoadBalancer 
   selector: 
     app: vote
   ports:
    - name: vote
      port: 80
      targetPort: 80  
